name: Auto Commit

on:
  push:
    branches:
      - diandian_devlop

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make some changes
        run: |
          echo "Some changes" >> file.txt
          git config --global user.name "DianDian"
          git config --global user.email "yilindiandian@gmail.com"
          git add file.txt
          git commit -m "Auto commit"

      - name: Push changes
        uses: github-actions-x/commit@v2
        with:
          github_token: ${{ secrets.PAT }}
          branch: diandian_devlop

